config/routes.rb
Rails.application.routes.draw do
  resources :areas

  resources :types

  resources :books

  devise_for :users
  resources :users
  
  root 'books#index'

end

app/models/area.rb
class Area < ActiveRecord::Base
    has_many :books
    #Validacion de campos obligatorios
    validates :name, presence: true
end

app/models/book.rb
class Book < ActiveRecord::Base
    belongs_to :type
    belongs_to :area

    #Validacion de campos obligatorios
    validates :title, presence: true
    validates :author, presence: true
    validates :description, presence: true
    validates :publication_date, presence: true
    validates :isbn, presence: true
    validates :type_id, presence: true
    validates :area_id, presence: true
    #Validacion de valor unico para el campo isbn
    validates :isbn, uniqueness: true
    #Validacion de valor minimo para la descripcion
    validates :description, length: { minimum: 30 }

    def self.searchTitle(search)
     if search
        where(['title LIKE ?', "%#{search}%"])
     else
        all
     end
    end
    
    def self.searchAuthor(search)
     if search
        where(['author LIKE ?', "%#{search}%"])
     else
        all
     end
    end
    
    def self.searchType(search)
    
     if search.to_i > 0
        where(['type_id = ? ', search.to_i ])
     else
        all
     end
    end
end

app/models/type.rb
class Type < ActiveRecord::Base
    has_many :books
    #Validacion de campos obligatorios
    validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  #Validacion de campos obligatorios
  validates :name, presence: true
  validates :lastname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u| 
      u.permit(:name, :lastname, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u| 
      u.permit(:name, :lastname, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @areas = Area.all
    respond_with(@areas)
  end

  def show
    respond_with(@area)
  end

  def new
    @area = Area.new
    respond_with(@area)
  end

  def edit
  end

  def create
    @area = Area.new(area_params)
    @area.save
    respond_with(@area)
  end

  def update
    @area.update(area_params)
    respond_with(@area)
  end

  def destroy
    @area.destroy
    respond_with(@area)
  end

  private
    def set_area
      @area = Area.find(params[:id])
    end

    def area_params
      params.require(:area).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :get_types, only: [:new, :edit, :create, :update, :destroy, :index]
  before_action :get_areas,only: [:new, :edit, :create, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  
  respond_to :html

  def index
    @books = Book.searchTitle(params[:title]).searchAuthor(params[:author]).searchType(params[:type]).order("publication_date DESC, title, author")
    respond_with(@books)
  end

  def show
    respond_with(@book)
  end

  def new
    @book = Book.new
    respond_with(@book)
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @book.save
    respond_with(@book)
  end

  def update
    @book.update(book_params)
    respond_with(@book)
  end

  def destroy
    @book.destroy
    respond_with(@book)
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :description, :publication_date, :isbn, :type_id, :area_id)
    end
    
    def get_types
      @types = Type.all.map{|type| [type.name, type.id]}
    end
    
    def get_areas
      @areas = Area.all.map{|area| [area.name, area.id]}
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @types = Type.all
    respond_with(@types)
  end

  def show
    respond_with(@type)
  end

  def new
    @type = Type.new
    respond_with(@type)
  end

  def edit
  end

  def create
    @type = Type.new(type_params)
    @type.save
    respond_with(@type)
  end

  def update
    @type.update(type_params)
    respond_with(@type)
  end

  def destroy
    @type.destroy
    respond_with(@type)
  end

  private
    def set_type
      @type = Type.find(params[:id])
    end

    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit class:'button' %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<h1>Listing areas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path, class: 'button' %>

app/views/areas/new.html.erb
<h1>New area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @area.name %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :publication_date %><br>
    <%= f.date_select :publication_date %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.select :type_id, @types %>
  </div>
  <div class="field">
    <%= f.label :area_id %><br>
    <%= f.select :area_id, @areas %>
  </div>
  <div class="actions">
    <%= f.submit class: 'button' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<div class="row">
  <%= form_tag(books_path, method: "get") do %>
    <div class="columns large-3">
      <%= label_tag(:title, "Title:") %>
      <%= text_field_tag(:title,params[:title]) %>
    </div>
    <div class="columns large-3">
      <%= label_tag(:author, "Author:") %>
      <%= text_field_tag(:author,params[:author]) %>
    </div>
    <div class="columns large-3">
      <%= label_tag(:type, "Type:") %>
      <%= select_tag(:type, options_for_select(@types, params[:type]),:include_blank => true) %>
    </div>
    <%= submit_tag "Search", class:'button'  %>
  <% end %>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Publication date</th>
      <th>Isbn</th>
      <th>Type</th>
      <th>Area</th>
      <th></th>
      <% if user_signed_in? %>
      <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.publication_date %></td>
        <td><%= book.isbn %></td>
        <td><%= book.type.name %></td>
        <td><%= book.area.name %></td>
        <td><%= link_to 'Show', book %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Book', new_book_path, class:'button' %>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Publication date:</strong>
  <%= @book.publication_date %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Type:</strong>
  <%= @book.type.name %>
</p>

<p>
  <strong>Area:</strong>
  <%= @book.area.name %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Bibliosoft" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1>
            <%= link_to 'Start', root_path %>
          </h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
    
      <section class="top-bar-section">
        <ul class="left">
          <li>
            <%= link_to 'Books', books_path %>
          </li>
          <% if user_signed_in? %>
          <li>
            <%= link_to 'Types', types_path %>
          </li>
          <li>
            <%= link_to 'Areas', areas_path %>
          </li>
          <% end %>
        </ul>
        
        <ul class="right">
          <% if user_signed_in? %>
            <li class="active">
              <%= link_to current_user.name.upcase, edit_user_registration_path %>            </li>
            <li>
              <%= link_to 'New User', new_user_registration_path %>
            </li>
            <li>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Sign In', user_session_path %>
            </li>
          <% end %>
        </ul>
      </section>
    </nav>
    
    <% if flash[:notice] %>
      <div data-alert class="alert-box info radius">
        <%= flash[:notice] %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div data-alert class="alert-box warning radius">
        <%= flash[:alert] %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div data-alert class="alert-box alert radius">
        <%= flash[:error] %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
    
    <div class="row">
      <div class="columns large-12">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit class: 'button' %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>Listing types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path,class:'button' %>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>